# coding: utf-8

# flake8: noqa
"""
    BRP Update API

    Met deze API kun je opvragen welke door jou gevolgde personen zijn gewijzigd in de BRP. Je kunt je abonneren op een persoon die je wilt volgen, en je kunt opvragen welke personen door jou worden gevolgd. Je kunt deze API gebruiken in combinatie met de BRP bevragen API, bijvoorbeeld om lokale kopiegegevens actueel te houden.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.models.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.models.foutbericht import Foutbericht
from openapi_client.models.gewijzigdepersonen_hal_collectie import GewijzigdepersonenHalCollectie
from openapi_client.models.gewijzigdepersonen_hal_collection_links import GewijzigdepersonenHalCollectionLinks
from openapi_client.models.hal_link import HalLink
from openapi_client.models.invalid_params import InvalidParams
from openapi_client.models.volgindicatie import Volgindicatie
from openapi_client.models.volgindicatie_collectie import VolgindicatieCollectie
from openapi_client.models.volgindicatie_raadplegen import VolgindicatieRaadplegen
from openapi_client.models.volgindicatie_raadplegen_all_of import VolgindicatieRaadplegenAllOf
