/*
 * BRP Update API
 * Met deze API kun je opvragen welke door jou gevolgde personen zijn gewijzigd in de BRP. Je kunt je abonneren op een persoon die je wilt volgen, en je kunt opvragen welke personen door jou worden gevolgd. Je kunt deze API gebruiken in combinatie met de BRP bevragen API, bijvoorbeeld om lokale kopiegegevens actueel te houden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.HalLink;

/**
 * GewijzigdepersonenHalCollectionLinks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-19T08:46:35.638Z[Etc/UTC]")
public class GewijzigdepersonenHalCollectionLinks {
  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private HalLink self;

  public static final String SERIALIZED_NAME_INGESCHREVEN_PERSOON = "ingeschrevenPersoon";
  @SerializedName(SERIALIZED_NAME_INGESCHREVEN_PERSOON)
  private HalLink ingeschrevenPersoon;


  public GewijzigdepersonenHalCollectionLinks self(HalLink self) {
    
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getSelf() {
    return self;
  }


  public void setSelf(HalLink self) {
    this.self = self;
  }


  public GewijzigdepersonenHalCollectionLinks ingeschrevenPersoon(HalLink ingeschrevenPersoon) {
    
    this.ingeschrevenPersoon = ingeschrevenPersoon;
    return this;
  }

   /**
   * Get ingeschrevenPersoon
   * @return ingeschrevenPersoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getIngeschrevenPersoon() {
    return ingeschrevenPersoon;
  }


  public void setIngeschrevenPersoon(HalLink ingeschrevenPersoon) {
    this.ingeschrevenPersoon = ingeschrevenPersoon;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GewijzigdepersonenHalCollectionLinks gewijzigdepersonenHalCollectionLinks = (GewijzigdepersonenHalCollectionLinks) o;
    return Objects.equals(this.self, gewijzigdepersonenHalCollectionLinks.self) &&
        Objects.equals(this.ingeschrevenPersoon, gewijzigdepersonenHalCollectionLinks.ingeschrevenPersoon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, ingeschrevenPersoon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GewijzigdepersonenHalCollectionLinks {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    ingeschrevenPersoon: ").append(toIndentedString(ingeschrevenPersoon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

