/*
 * BRP Update API
 * Met deze API kun je opvragen welke door jou gevolgde personen zijn gewijzigd in de BRP. Je kunt je abonneren op een persoon die je wilt volgen, en je kunt opvragen welke personen door jou worden gevolgd. Je kunt deze API gebruiken in combinatie met de BRP bevragen API, bijvoorbeeld om lokale kopiegegevens actueel te houden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GewijzigdepersonenHalCollectionLinks;

/**
 * GewijzigdepersonenHalCollectie
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-13T13:13:10.541Z[Etc/UTC]")
public class GewijzigdepersonenHalCollectie {
  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private GewijzigdepersonenHalCollectionLinks links;

  public static final String SERIALIZED_NAME_BURGERSERVICENUMMERS = "burgerservicenummers";
  @SerializedName(SERIALIZED_NAME_BURGERSERVICENUMMERS)
  private List<String> burgerservicenummers = null;


  public GewijzigdepersonenHalCollectie links(GewijzigdepersonenHalCollectionLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GewijzigdepersonenHalCollectionLinks getLinks() {
    return links;
  }


  public void setLinks(GewijzigdepersonenHalCollectionLinks links) {
    this.links = links;
  }


  public GewijzigdepersonenHalCollectie burgerservicenummers(List<String> burgerservicenummers) {
    
    this.burgerservicenummers = burgerservicenummers;
    return this;
  }

  public GewijzigdepersonenHalCollectie addBurgerservicenummersItem(String burgerservicenummersItem) {
    if (this.burgerservicenummers == null) {
      this.burgerservicenummers = new ArrayList<>();
    }
    this.burgerservicenummers.add(burgerservicenummersItem);
    return this;
  }

   /**
   * Get burgerservicenummers
   * @return burgerservicenummers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getBurgerservicenummers() {
    return burgerservicenummers;
  }


  public void setBurgerservicenummers(List<String> burgerservicenummers) {
    this.burgerservicenummers = burgerservicenummers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GewijzigdepersonenHalCollectie gewijzigdepersonenHalCollectie = (GewijzigdepersonenHalCollectie) o;
    return Objects.equals(this.links, gewijzigdepersonenHalCollectie.links) &&
        Objects.equals(this.burgerservicenummers, gewijzigdepersonenHalCollectie.burgerservicenummers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, burgerservicenummers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GewijzigdepersonenHalCollectie {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    burgerservicenummers: ").append(toIndentedString(burgerservicenummers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

