baseurl: "/Haal-Centraal-BRP-Update-API"
apiname: "BRP Update API"
url: "http://localhost:4000"
# M.b.v. de optionele variabele 'logo' kan een ander logo dan het VNG logo in de rechterbovenhoek geplaatst worden.
# Het betreffende bestand zal dan wel in de folder '\assets\img' van het remote the 'VNG-Realisatie/jekyll-theme-haal-centraal' moeten worden geplaatst.
# Met de variabele 'organisation-url' kan de link onder het logo worden bepaald.
logo: "BZK_RIG_Logo_online_ex_pos_nl.png"
organisation-url: "http://www.rvig.nl"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: BRP Update API
    subnav:
      - title: Main
        path: /
#      - title: Goals canvas
#        path: /goals-canvas
  - title: Specificaties v. 1.0 (IO)
    subnav:
      - title: Getting started
        path: /getting-started
      - title: User stories
        url: user-stories-prod
        path: /user-stories
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
      - title: Bevragen API (redoc)
        path: /redoc
      - title: Features
        path: /features
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: BRP-API/Haal-Centraal-BRP-Update-API

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal-BRP-Update-API
