# coding: utf-8

# flake8: noqa

"""
    BRP Update API

    Met deze API kun je opvragen welke door jou gevolgde personen zijn gewijzigd in de BRP. Je kunt je abonneren op een persoon die je wilt volgen, en je kunt opvragen welke personen door jou worden gevolgd. Je kunt deze API gebruiken in combinatie met de BRP bevragen API, bijvoorbeeld om lokale kopiegegevens actueel te houden.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.beheren_volgindicaties_api import BeherenVolgindicatiesApi
from openapi_client.api.raadplegen_gewijzigde_personen_api import RaadplegenGewijzigdePersonenApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.models.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.models.foutbericht import Foutbericht
from openapi_client.models.gewijzigdepersonen_hal_collectie import GewijzigdepersonenHalCollectie
from openapi_client.models.gewijzigdepersonen_hal_collection_links import GewijzigdepersonenHalCollectionLinks
from openapi_client.models.hal_link import HalLink
from openapi_client.models.invalid_params import InvalidParams
from openapi_client.models.volgindicatie import Volgindicatie
from openapi_client.models.volgindicatie_collectie import VolgindicatieCollectie
from openapi_client.models.volgindicatie_raadplegen import VolgindicatieRaadplegen
from openapi_client.models.volgindicatie_raadplegen_all_of import VolgindicatieRaadplegenAllOf

